version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}



  crypto_app:
    build:
      context: .
    env_file:
      - .env
    container_name: crypto_app
    ports:
      - 8080:8000
    volumes:
      - .:/src
    depends_on:
      - postgres
    environment:
      - PYTHONPATH=/src


volumes:
  pg_data: