"""updata crypto table

Revision ID: 35b12d70c708
Revises: e099681c5743
Create Date: 2023-10-24 20:23:49.610661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35b12d70c708'
down_revision: Union[str, None] = 'e099681c5743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crypto_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('current_price', sa.Integer(), nullable=True),
    sa.Column('market_cap', sa.Integer(), nullable=True),
    sa.Column('market_cap_rank', sa.Integer(), nullable=True),
    sa.Column('fully_diluted_valuation', sa.Integer(), nullable=True),
    sa.Column('total_volume', sa.Integer(), nullable=True),
    sa.Column('high_24h', sa.Integer(), nullable=True),
    sa.Column('low_24h', sa.Integer(), nullable=True),
    sa.Column('price_change_24h', sa.Integer(), nullable=True),
    sa.Column('price_change_percentage_1h', sa.Integer(), nullable=True),
    sa.Column('price_change_percentage_24h', sa.Integer(), nullable=True),
    sa.Column('price_change_percentage_7d', sa.Integer(), nullable=True),
    sa.Column('price_change_percentage_30d', sa.Integer(), nullable=True),
    sa.Column('price_change_percentage_1y', sa.Integer(), nullable=True),
    sa.Column('market_cap_change_24h', sa.Integer(), nullable=True),
    sa.Column('market_cap_change_percentage_24h', sa.Integer(), nullable=True),
    sa.Column('circulating_supply', sa.Integer(), nullable=True),
    sa.Column('total_supply', sa.Integer(), nullable=True),
    sa.Column('max_supply', sa.Integer(), nullable=True),
    sa.Column('ath', sa.Integer(), nullable=True),
    sa.Column('ath_change_percentage', sa.Integer(), nullable=True),
    sa.Column('atl_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_updated', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crypto')
    # ### end Alembic commands ###
