"""add float

Revision ID: dbad350b7db2
Revises: 7cf5be525e8c
Create Date: 2023-10-27 19:59:42.911034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbad350b7db2'
down_revision: Union[str, None] = '7cf5be525e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crypto', 'current_price',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('crypto', 'market_cap',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('crypto', 'fully_diluted_valuation',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('crypto', 'total_volume',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('crypto', 'high_24h',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('crypto', 'low_24h',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('crypto', 'price_change_24h',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('crypto', 'price_change_percentage_1h',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('crypto', 'price_change_percentage_24h',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('crypto', 'price_change_percentage_7d',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('crypto', 'price_change_percentage_30d',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('crypto', 'price_change_percentage_1y',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('crypto', 'market_cap_change_24h',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('crypto', 'market_cap_change_percentage_24h',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('crypto', 'circulating_supply',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('crypto', 'total_supply',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('crypto', 'max_supply',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('crypto', 'ath',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('crypto', 'ath_change_percentage',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crypto', 'ath_change_percentage',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('crypto', 'ath',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('crypto', 'max_supply',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('crypto', 'total_supply',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('crypto', 'circulating_supply',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('crypto', 'market_cap_change_percentage_24h',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('crypto', 'market_cap_change_24h',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('crypto', 'price_change_percentage_1y',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('crypto', 'price_change_percentage_30d',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('crypto', 'price_change_percentage_7d',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('crypto', 'price_change_percentage_24h',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('crypto', 'price_change_percentage_1h',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('crypto', 'price_change_24h',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('crypto', 'low_24h',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('crypto', 'high_24h',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('crypto', 'total_volume',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('crypto', 'fully_diluted_valuation',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('crypto', 'market_cap',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('crypto', 'current_price',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
